### ISSUE TITLE
Tycoon-Idle-type-game-thingy 

### ISSUE THREAD

**Issue by CarolsCastle** [zThana/PlanetEris#2]
I was thinking..

You can start up a business of some sort.. kind of like Idle Mine, BUT Eris themed.

I haven’t thought that far but *let’s say it’s a* Café ...
This is just a quick sample:
`>café start`
*gives me x amount to open a shop (only for 1st timers)*
`>Café open`
*Costs me x amount and Opens a my first or new Café*
`>sell` or `>s` *to sell coffee*
`>upgrade coffee` or `>up c` *will upgrade coffee to next level making coffee more valuable*
`>up storage (?)` or `up st (?)` or maybe call it something else but.. *it’ll increase storage space of earning*
- if the storage is full, you can’t earn more money until you `>sell`

`>Café profile`
🌸   Shows how much 💰 (money) 
🌸   How many Café you own and its level.
🌸   Coffee level and earnings
🌸   Storage level and capacity 
🌸   maybe more info

Also you can only have more Café’s by reaching a certain coffee and storage prestige. Say it’s both maxed to level 100
Then you can have another Café or not. And instead upgrade the Café itself.

✏️ So not Café - it’s just a sample. It could be Flowerfield or something 💜
✏️ Oh this would/could be a global thing (?)

🔮 if not a global game then hopefully customized by server owner. and you would not need `>something start` and instead use the balance you have in that server!
Meaning if the owner customized it to be a Café the everyone can `>open` their own Café in that server and check `>top Café` to see who’s Café is most successful.
✨ That way if you’re in another server e.g. **Eris’ Flowerfield**, maybe Thana makes the shop there a Flowershop... then I can `>open flowershop` and start earning there too.

**Comment by zThana** [comment]
I like the idea but Idle Miner already does a great job at accomplishing this and has pretty much everything other than being able to customize the name / style.
Nice idea but I have no plans for it.
